<?php

namespace Jiwon\CCCPBundle\Repository;

/**
 * ResultatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatRepository extends \Doctrine\ORM\EntityRepository
{
	public function mostRecentDate()
    {
        $query = $this->createQueryBuilder('r')
        	->select('MAX(r.date)')
        	->setMaxResults(1)
        	->orderBy('r.date', 'DESC');

        return $query->getQuery()->getSingleScalarResult();
    }

	public function countResult($template = null, $entite = null, $categorie = null, $fonction = null, $reseau = null, $date = null)
    {
        $query = $this->createQueryBuilder('r')
        	->select('r.success as success')
        	->addSelect('r.failed as failed')
        	->innerJoin('r.id_association', 'a')
        	->innerJoin('a.id_categorie', 'c')
        	->where('1 = 1');

        if($template != null) {
        	$query
        		->andWhere('r.id_template = :template')
        		->setParameter('template', $template->getId());
        }
        if($entite != null) {
        	$query
        		->andWhere('a.id_entite = :entite')
        		->setParameter('entite', $entite->getId());
        }
        if($fonction != null) {
        	$query
        		->andWhere('a.id_fonction = :fonction')
        		->setParameter('fonction', $fonction->getId());
        }
        if($categorie != null) {
        	$query
        		->andWhere('a.id_categorie = :categorie')
        		->setParameter('categorie', $categorie->getId());
        }
        if($reseau != null) {
        	$query
                ->andWhere('a.id_reseau = :reseau')
                ->setParameter('reseau', $reseau->getId());
        }
        if($date != null) {
            $query
                ->andWhere('r.date = :date')
                ->setParameter('date', $date);
        }

        $query
            ->setMaxResults(1)
            ->orderBy('r.date', 'DESC');

        return $query->getQuery()->getOneOrNullResult();
    }
}
