# src/OC/PlatformBundle/Resources/config/routing.yml

# Page d'accueil
oc_platform_home:
    path:      /{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

# Page de visualisation d'une annonce
oc_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+

# Ajout d'une annonce    
oc_platform_add:
    path:      /add
    defaults:
        _controller: OCPlatformBundle:Advert:add
    
# Edition d'une annonce
oc_platform_edit:
    path:      /edit/{id}
    defaults: { _controller: OCPlatformBundle:Advert:edit }
    requirements:
        id: \d+

# Suppresion d'une annonce
oc_platform_delete:
    path:      /delete/{id}
    defaults: { _controller: OCPlatformBundle:Advert:delete }
    requirements:
        id: \d+

# Modification de l'image d'une annonce
oc_platform_edit_image:
    path: /advert/editImage/{advertId}
    defaults: { _controller: OCPlatformBundle:Advert:editImage }
    requirements:
        advertId: \d+