<?php

namespace Jiwon\AuditBundle\Repository;

/**
 * CrontabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrontabRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrdered()
    {
    	$qb = $this->createQueryBuilder('a')
			->leftJoin('a.id_template', 'template')
			->addSelect('template')
			->leftJoin('template.id_association', 'asso')
			->addSelect('asso')
			->leftJoin('asso.id_reseau', 'reseau')
			->addSelect('reseau')
			->leftJoin('asso.id_type_ne', 'type')
			->addSelect('type')
			->leftJoin('template.id_constructeur', 'cons')
			->addSelect('cons')
			->leftJoin('template.id_modele', 'model')
			->addSelect('model')
			->orderBy('reseau.reseau', 'ASC')
			->addOrderBy('type.type', 'ASC')
			->addOrderBy('cons.constructeur', 'ASC')
			->addOrderBy('model.model', 'ASC')
			->addOrderBy('template.nom', 'ASC')
			->addOrderBy('a.heure', 'ASC')
			->addOrderBy('a.recurrence', 'ASC')
  		;

  		return $qb->getQuery()->getResult();
    }

    public function findAllWithTemplate($id)
    {
    	$qb = $this->createQueryBuilder('a')
			->where('a.id_template = :id')
			->setParameter('id', $id);
  		;

  		return $qb->getQuery()->getResult();
    }
}
