<?php

namespace Jiwon\AuditBundle\Repository;

/**
 * ExportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExportRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrdered()
    {
    	$qb = $this->createQueryBuilder('a')
			->orderBy('a.nom', 'ASC')
  		;

  		return $qb->getQuery()->getResult();
    }
}
