<?php

namespace Jiwon\AuditBundle\Repository;

/**
 * VariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariableRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllWithTemplate($id)
    {
    	$qb = $this->createQueryBuilder('a')
			->where('a.id_template = :id')
			->setParameter('id', $id);
  		;

  		return $qb->getQuery()->getResult();
    }
}
